server {
    listen 80;
    server_name joum.anacas.dev;

    location / {
        proxy_pass http://backend:8000;  # Asegúrate de que esta URL coincida con la configuración del contenedor backend
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
