version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:8000"
    env_file:
      - ./backend/.env
    restart: always
    container_name: backend
    labels:
      - coolify.version=4.0.0-beta.420.1
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=backend
      - traefik.enable=true

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:3000"
    restart: always
    container_name: frontend
    labels:
      - coolify.version=4.0.0-beta.420.1
      - coolify.applicationId=1
      - coolify.type=application
      - coolify.name=frontend
      - traefik.enable=true
