version: '3.8'
services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    volumes:
      - /data/coolify/applications/pgg4owow4o44g4c8okc84w88/backend:/app
    restart: always
    entrypoint: uvicorn main:app --host 0.0.0.0 --port 8000
    container_name: backend-pgg4owow4o44g4c8okc84w88-15435386668
    labels:
      - coolify.version=4.0.0-beta.420.1
      - coolify.applicationId-1
      - coolify.type=application
      - coolify.name=backend-pgg4owow4o44g4c8okc84w88-15435386668

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    restart: always
    entrypoint: npm run build && nginx -g 'daemon off;'
    container_name: frontend-pgg4owow4o44g4c8okc84w88-15435386668
    labels:
      - coolify.version=4.0.0-beta.420.1
      - coolify.applicationId=2
      - coolify.type=application
      - coolify.name=frontend-pgg4owow4o44g4c8okc84w88-15435386668

